### ISSUE TITLE
Black highlighting

### ISSUE THREAD

**Issue by bklebe** [ogham/Rust-BBEdit#2]
It seems the default highlighting for a few functions is black, making it unreadable on dark color schemes. What scheme are you using?

**Comment by ogham** [comment]
I use a light colour scheme, but I think I know the issue - the colours reset to black when you change the scheme? This seems to be a BBEdit issue, as I have a [`BBLMRunColors`](https://github.com/ogham/Rust.bblm/blob/6bc2dac873dce1744b73aa5adf115b487822fe5d/info.plist#L51) dict that sets them the first time, but any other colour schemes don't have them, so they just get set to black. I'm not sure what to do about this :(

**Comment by jolux** [comment]
Hi Ben,

It's any time I use it. I can't tell what's causing it either. Should we file a big with barebones?

**Comment by ogham** [comment]
Even after you change the colours in Preferences -> Text Colors, they just reset to black?

**Comment by jolux** [comment]
It's not so much that they reset to black but that they never appear to be anything else to me. It's impossible to read. Here's the problem:
![screen shot 2015-05-06 at 8 03 10 pm](https://cloud.githubusercontent.com/assets/9062973/7506214/f1e7c09c-f42a-11e4-8221-85f78056e9fa.png)

**Comment by ogham** [comment]
Yeah, that's what I get too - the built-in colour schemes don't have these colours defined, so they just get set to black instead. You need to click on the rectangles to open the colour pickers, and then you can set them to colours that match your scheme.

**Comment by ogham** [comment]
Sorry if you knew that already. It might be worth e-mailing Bare Bones to apply the `BBLMRunColors` colours if they aren't present in the scheme. (I'm pretty sure I've got it set up correctly in the plist)

**Comment by jolux** [comment]
On 6 May 2015, at 21:40, Ben S wrote:

> Sorry if you knew that already. It might be worth e-mailing Bare Bones 
> to apply the `BBLMRunColors` colours if they aren't present in the 
> scheme. (I'm pretty sure I've got it set up correctly in the plist)
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/ogham/Rust.bblm/issues/2#issuecomment-99673736

Yeah I absolutely knew that already. I've been hacking on BBEdit syntax 
highlighting for several months now and was just making sure you knew 
what your defaults were. I know I can change those colors but that 
creates an entirely different scheme which further reduces the 
portability of my setup across installations. I assumed there was a way 
to specify a generic scheme for coloring something that would apply 
different colors that would be theme-specific. I know now that there 
isn't. I might end up sending a feature request for that if it isn't 
already on their roadmap or isn't already possible because they seem to 
be opening up the syntax highlighting a bit these days.

Sincerely,

Ben Klebe

**Comment by ogham** [comment]
This was in the 11.1.1 release notes:

> Fixed bug in which custom color schemes were written out incorrectly, so that their settings did not appropriately override built in defaults.

Maybe this fixes it?

**Comment by jolux** [comment]
No, that doesn't seem to have fixed it. That's referring to themes, not to CLMs such as this one.

**Comment by ogham** [comment]
Dang :(
